---

- name: AWS-Docker-Ansible Setup
  hosts: local
  connection: local
  gather_facts: False


  vars_files:
    - info/aws-credentials.yml
    - info/specs.yml

  tasks:
  - name: Create security group
    ec2_group:
      name: AWS-Docker-Ansible-group
      description: "A Security group"
      region: "{{aws_region}}"
      vpc_id: "{{ vpc_id }}"
      aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
      aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"      
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: "{{ cidr_range }}"
        - proto: tcp
          from_port: 5601
          to_port: 5601
          cidr_ip: "{{ cidr_range }}"
        - proto: tcp
          from_port: 9200
          to_port: 9200
          cidr_ip: "{{ cidr_range }}"
        - proto: tcp
          from_port: 8081
          to_port: 8081
          cidr_ip: "{{ cidr_range }}"
      rules_egress:
      - proto: all
        from_port: 0
        to_port: 65535
        cidr_ip: 0.0.0.0/0
    register: firewall


  - name: Create EC-2 instance
    ec2:
      aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
      aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
      vpc_subnet_id: "{{ vpc_subnet_id }}"
      region: "{{ aws_region }}"
      group_id: "{{ firewall.group_id }}"   
      instance_type: "{{ instance_type }}"
      image: "{{ ami_id }}"
      key_name: "{{ key_name }}"
      instance_tags:
            Name: "{{ tags_used }}"
      exact_count: 1
      count_tag:
            Name: "{{ tags_used }}"
      wait: true
      assign_public_ip: yes
    register: ec2
